version: '3.8'

services:
  upgrade-bot:
    build: .
    container_name: upgrade-bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./upgrade.db:/app/upgrade.db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
